parameters:
    crocos_security.auth_logic.session_entity.class: Crocos\SecurityBundle\Security\AuthLogic\SessionEntityAuth

services:
    crocos_security.auth_logic.session_entity:
        class: %crocos_security.auth_logic.session_entity.class%
        arguments:
            - @session
            - @doctrine
        tags:
            - { name: crocos_security.auth_logic, alias: session.entity }
