build:
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=clover.xml'
        coverage:
          file: 'clover.xml'
          format: 'php-clover'

filter:
  excluded_paths:
    - 'Tests/*'
    - 'Resources/*'
